version: "3.1"

networks:
    backend:
        driver: bridge

services:
    postgres:
        image: 10.3.142.201:5000/5024201073-its-gram-postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: its-gram
        networks:
            - backend

    api:
        image: 10.3.142.201:5000/5024201073-its-gram-api:latest
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - postgres
        networks:
            - backend
