version: "3.1"

services:
    postgres:
        # image: postgres
        image: 10.3.142.201:5000/5024201073-its-gram-postgres:latest
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:${DB_PORT}

    api:
        # build: .
        image: 10.3.142.201:5000/5024201073-its-gram-api:latest
        restart: always
        ports:
            - ${DEV_PORT}:${DEV_PORT}
        depends_on:
            - postgres
